#!/usr/bin/env python3
"""Explicitly refresh the CPU lock from canonical app metadata; uses the network.

This is a maintainer operation, never part of assembly or installation. Review
new artifacts and hashes before replacing the checked-in lock.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
from pathlib import Path
import subprocess

import prepare


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    work = args.directory.resolve(strict=True)
    pins = json.loads((prepare.HERE / "inputs.json").read_text())
    tree = ast.parse((work / "app-source/src/nvbroadcast/runtime/variants.py").read_text())
    version = next(ast.literal_eval(n.value) for n in tree.body if isinstance(n, ast.Assign)
                   and any(isinstance(t, ast.Name) and t.id == "FASTER_WHISPER_VERSION" for t in n.targets))
    requirements = []
    for name, pattern in (("nvbroadcast[cpu,meeting-support]", "nvbroadcast-*.whl"),
                          ("pycairo", "pycairo-*.whl"), ("PyGObject", "pygobject-*.whl")):
        wheels = list((work / "wheels").glob(pattern))
        if len(wheels) != 1:
            raise ValueError(f"expected one local wheel for {name}")
        requirements.append(f"{name} @ {wheels[0].as_uri()}")
    requirements.append(f"faster-whisper=={version}")
    source = work / "application-requirements.in"
    source.write_text("\n".join(requirements) + "\n")
    # Re-extract the verified uv archive so an altered cached executable is not
    # implicitly trusted during a lock update.
    prepare.unpack_uv(work / "inputs" / prepare.filename(pins["uv"]),
                      pins["uv"], work / "resolver")
    subprocess.run([
        str(work / "resolver/uv-x86_64-unknown-linux-gnu/uv"), "pip", "compile", str(source),
        "--python", str(work / "builder-python/runtime/bin/python"),
        "--python-version", pins["python"]["version"], "--no-python-downloads",
        "--python-platform", "x86_64-manylinux_2_28", "--only-binary", ":all:",
        "--format", "pylock.toml", "-o", str(args.output),
    ], check=True)
    # PEP 751 local paths should be portable between workspace locations.
    content = args.output.read_text()
    for wheel in (work / "wheels").glob("*.whl"):
        content = content.replace(json.dumps(str(wheel)),
                                  json.dumps(os.path.relpath(wheel, args.output.resolve().parent)))
    # Do not publish machine-specific workspace paths in uv's command comment.
    content = "# Generated by resolve.py using the pinned uv release.\n" + "\n".join(
        line for line in content.splitlines() if not line.startswith("#")
    ) + "\n"
    args.output.write_text(content)


if __name__ == "__main__":
    main()
