#!/usr/bin/env python3
"""Validate the Python dependency closure inside an extracted Snap."""

from __future__ import annotations

import argparse
import configparser
import importlib
from importlib import metadata
import os
from pathlib import Path
import re
import shlex
import sys

import packaging
from packaging.markers import default_environment
from packaging.requirements import InvalidRequirement, Requirement
from packaging.specifiers import SpecifierSet
from packaging.utils import canonicalize_name


REQUIRED_RUNTIME = {
    "numpy": SpecifierSet(">=1.26"),
    "packaging": SpecifierSet(">=26.0"),
    "protobuf": SpecifierSet(">=5.29.6"),
    "setuptools": SpecifierSet(">=83.0.0"),
    "opencv-contrib-python": SpecifierSet(">=4.8.1.78,<5"),
}
IMPORT_PROBES = ("packaging", "setuptools")
ARCHITECTURES = {
    "amd64": "x86_64",
    "x86_64": "x86_64",
    "arm64": "aarch64",
    "aarch64": "aarch64",
}
FORBIDDEN_BUILD_PATH = re.compile(
    r"/build(?:/|$)|/snap/[^/\s]*-sdk(?:/|$)"
)
CORE24_PYTHON = re.compile(r"^/usr/bin/python3(?:\.\d+)*$")
GNOME_PLATFORM_SHADOWS = (
    "usr/lib/*/libadwaita-1.so*",
    "usr/lib/*/libgdk_pixbuf-2.0.so*",
    "usr/lib/*/libgtk-4.so*",
    "usr/lib/*/libgstreamer-1.0.so*",
    "usr/lib/*/librsvg-2.so*",
)


def discover_package_roots(snap_root: Path) -> list[Path]:
    patterns = (
        "lib/python*/site-packages",
        "lib/python*/dist-packages",
        "usr/lib/python*/site-packages",
        "usr/lib/python*/dist-packages",
        "usr/local/lib/python*/site-packages",
        "usr/local/lib/python*/dist-packages",
    )
    roots = {
        path.resolve()
        for pattern in patterns
        for path in snap_root.glob(pattern)
        if path.is_dir()
    }
    return sorted(roots)


def python_runtime_problems(snap_root: Path) -> list[str]:
    """Validate that the packaged venv resolves only runtime-accessible paths."""
    pyvenv = snap_root / "pyvenv.cfg"
    if not pyvenv.is_file():
        return ["Snap is missing pyvenv.cfg"]

    contents = pyvenv.read_text()
    problems: list[str] = []
    if forbidden := FORBIDDEN_BUILD_PATH.search(contents):
        problems.append(
            f"pyvenv.cfg contains build-only path {forbidden.group(0)!r}"
        )

    parser = configparser.ConfigParser(interpolation=None)
    try:
        parser.read_string(f"[venv]\n{contents}")
    except configparser.Error as error:
        problems.append(f"pyvenv.cfg is invalid: {error}")
    else:
        home = parser["venv"].get("home")
        if home != "/usr/bin":
            problems.append(
                f"pyvenv.cfg must use core24 Python home /usr/bin, found {home!r}"
            )

    python_link = snap_root / "bin/python3"
    if not python_link.is_symlink():
        problems.append("Snap is missing the bin/python3 runtime symlink")
    else:
        target = os.readlink(python_link)
        if not CORE24_PYTHON.fullmatch(target):
            problems.append(
                f"bin/python3 must target core24 Python, found {target!r}"
            )

    return problems


def platform_shadow_problems(snap_root: Path) -> list[str]:
    """Reject libraries that must come from the GNOME content snap."""
    shadows = {
        path.relative_to(snap_root)
        for pattern in GNOME_PLATFORM_SHADOWS
        for path in snap_root.glob(pattern)
    }
    return [
        f"Snap shadows a GNOME platform library: {path}"
        for path in sorted(shadows)
    ]


def desktop_launcher_problems(snap_root: Path) -> list[str]:
    """Validate the desktop launcher generated by Snapcraft."""
    launcher = snap_root / "meta/gui/nvbroadcast.desktop"
    if not launcher.is_file():
        return ["Snap is missing meta/gui/nvbroadcast.desktop"]

    parser = configparser.ConfigParser(interpolation=None)
    try:
        parser.read(launcher, encoding="utf-8")
    except (configparser.Error, OSError, UnicodeError) as error:
        return [f"Snap desktop launcher is invalid: {error}"]

    if not parser.has_section("Desktop Entry"):
        return ["Snap desktop launcher is missing the Desktop Entry section"]

    entry = parser["Desktop Entry"]
    problems: list[str] = []
    exec_value = entry.get("Exec", "")
    try:
        command = shlex.split(exec_value)
    except ValueError as error:
        problems.append(f"Snap desktop launcher has invalid Exec: {error}")
    else:
        if not command or command[0] != "nvbroadcast":
            problems.append(
                "Snap desktop launcher Exec must start with nvbroadcast, "
                f"found {exec_value!r}"
            )

    icon_value = entry.get("Icon", "")
    expected_icon = "${SNAP}/meta/gui/icon.svg"
    if icon_value != expected_icon:
        problems.append(
            f"Snap desktop launcher Icon must be {expected_icon}, "
            f"found {icon_value!r}"
        )
    else:
        icon = snap_root / "meta/gui/icon.svg"
        if not icon.is_file():
            problems.append(
                f"Snap desktop launcher icon does not exist: {icon_value}"
            )

    return problems


def _python_environment(
    package_roots: list[Path], platform_machine: str
) -> dict[str, str]:
    environment = default_environment()
    environment.update(
        os_name="posix",
        platform_machine=ARCHITECTURES[platform_machine],
        platform_system="Linux",
        sys_platform="linux",
        extra="",
    )

    versions = {
        match.groups()
        for root in package_roots
        if (match := re.search(r"python(\d+)\.(\d+)", str(root)))
    }
    if len(versions) == 1:
        major, minor = versions.pop()
        environment["python_version"] = f"{major}.{minor}"
        if (int(major), int(minor)) != sys.version_info[:2]:
            environment["python_full_version"] = f"{major}.{minor}.0"
    return environment


def _distribution_index(
    package_roots: list[Path],
) -> tuple[list[metadata.Distribution], dict[str, list[str]]]:
    distributions = list(
        metadata.distributions(path=[str(path) for path in package_roots])
    )
    installed: dict[str, list[str]] = {}
    for distribution in distributions:
        name = distribution.metadata.get("Name")
        if not name:
            continue
        installed.setdefault(canonicalize_name(name), []).append(distribution.version)
    return distributions, installed


def dependency_problems(
    snap_root: Path, platform_machine: str
) -> tuple[int, list[str]]:
    package_roots = discover_package_roots(snap_root)
    if not package_roots:
        return 0, ["no Python package roots were found"]

    distributions, installed = _distribution_index(package_roots)
    environment = _python_environment(package_roots, platform_machine)
    problems: list[str] = []

    for package_name, specifier in REQUIRED_RUNTIME.items():
        versions = installed.get(canonicalize_name(package_name), [])
        if not versions:
            problems.append(f"required runtime package is missing: {package_name}{specifier}")
        elif len(versions) != 1:
            problems.append(
                f"required runtime package has multiple owners: "
                f"{package_name} ({', '.join(versions)})"
            )
        elif not any(version in specifier for version in versions):
            problems.append(
                f"{package_name} versions {', '.join(versions)} do not satisfy {specifier}"
            )

    opencv_owners = {
        name: versions for name, versions in installed.items() if name.startswith("opencv-")
    }
    if set(opencv_owners) != {"opencv-contrib-python"}:
        rendered = ", ".join(
            f"{name} ({', '.join(versions)})"
            for name, versions in sorted(opencv_owners.items())
        )
        problems.append(f"Snap must have exactly one OpenCV owner; found: {rendered}")

    for distribution in distributions:
        owner = distribution.metadata.get("Name", "<unknown>")
        for raw_requirement in distribution.requires or ():
            try:
                requirement = Requirement(raw_requirement)
            except InvalidRequirement as error:
                problems.append(f"{owner} has invalid requirement {raw_requirement!r}: {error}")
                continue
            if requirement.marker and not requirement.marker.evaluate(environment):
                continue

            versions = installed.get(canonicalize_name(requirement.name), [])
            if not versions:
                problems.append(f"{owner} requires missing package {requirement}")
            elif requirement.specifier and not any(
                version in requirement.specifier for version in versions
            ):
                problems.append(
                    f"{owner} requires {requirement}, found {', '.join(versions)}"
                )

    return len(installed), sorted(set(problems))


def import_problems(package_roots: list[Path]) -> list[str]:
    problems = []
    for module_name in IMPORT_PROBES:
        try:
            module = importlib.import_module(module_name)
        except Exception as error:  # pragma: no cover - reported by artifact CI
            problems.append(f"cannot import {module_name}: {error}")
            continue
        module_path = Path(module.__file__).resolve()
        if not any(module_path.is_relative_to(root) for root in package_roots):
            problems.append(f"{module_name} resolved outside the Snap: {module_path}")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("snap_root", type=Path)
    parser.add_argument(
        "--platform-machine",
        required=True,
        choices=tuple(ARCHITECTURES),
    )
    args = parser.parse_args()

    snap_root = args.snap_root.resolve()
    package_roots = discover_package_roots(snap_root)
    count, problems = dependency_problems(snap_root, args.platform_machine)
    problems.extend(python_runtime_problems(snap_root))
    problems.extend(platform_shadow_problems(snap_root))
    problems.extend(desktop_launcher_problems(snap_root))
    problems.extend(import_problems(package_roots))

    if problems:
        for problem in sorted(set(problems)):
            print(f"ERROR: {problem}", file=sys.stderr)
        return 1

    print(
        f"Validated {count} Python distributions for "
        f"{ARCHITECTURES[args.platform_machine]}; packaging {packaging.__version__}, "
        "single-owner core runtime constraints are satisfied."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
