#!/usr/bin/env python3
"""Validate the Python dependency closure inside an extracted Snap."""

from __future__ import annotations

import argparse
import configparser
import os
from pathlib import Path
import re
import shlex
import sys

import packaging
from packaging.specifiers import SpecifierSet
from packaging.utils import canonicalize_name

from nvbroadcast.runtime.artifact import (
    ARCHITECTURES,
    ArtifactEnvironment,
    discover_package_roots,
)
from nvbroadcast.runtime.variants import (
    RUNTIME_CONTRACTS,
    RuntimeVariant,
    runtime_ownership_problems,
)


REQUIRED_RUNTIME = {
    "numpy": SpecifierSet(">=1.26"),
    "packaging": SpecifierSet(">=26.0"),
    "protobuf": SpecifierSet(">=5.29.6"),
    "setuptools": SpecifierSet(">=83.0.0"),
    "opencv-contrib-python": SpecifierSet(">=4.8.1.78,<5"),
}
IMPORT_PROBES = ("packaging", "setuptools", "onnxruntime")
RUNTIME_VERSION = SpecifierSet("==1.24.4")


def expected_variant(platform_machine: str) -> RuntimeVariant:
    return (
        RuntimeVariant.CUDA
        if ARCHITECTURES[platform_machine] == "x86_64"
        else RuntimeVariant.CPU
    )


FORBIDDEN_BUILD_PATH = re.compile(
    r"/build(?:/|$)|/snap/[^/\s]*-sdk(?:/|$)"
)
CORE24_PYTHON = re.compile(r"^/usr/bin/python3(?:\.\d+)*$")
GNOME_PLATFORM_SHADOWS = (
    "usr/lib/*/libadwaita-1.so*",
    "usr/lib/*/libgdk_pixbuf-2.0.so*",
    "usr/lib/*/libgtk-4.so*",
    "usr/lib/*/libgstreamer-1.0.so*",
    "usr/lib/*/librsvg-2.so*",
)


def python_runtime_problems(snap_root: Path) -> list[str]:
    """Validate that the packaged venv resolves only runtime-accessible paths."""
    pyvenv = snap_root / "pyvenv.cfg"
    if not pyvenv.is_file():
        return ["Snap is missing pyvenv.cfg"]

    contents = pyvenv.read_text()
    problems: list[str] = []
    if forbidden := FORBIDDEN_BUILD_PATH.search(contents):
        problems.append(
            f"pyvenv.cfg contains build-only path {forbidden.group(0)!r}"
        )

    parser = configparser.ConfigParser(interpolation=None)
    try:
        parser.read_string(f"[venv]\n{contents}")
    except configparser.Error as error:
        problems.append(f"pyvenv.cfg is invalid: {error}")
    else:
        home = parser["venv"].get("home")
        if home != "/usr/bin":
            problems.append(
                f"pyvenv.cfg must use core24 Python home /usr/bin, found {home!r}"
            )

    python_link = snap_root / "bin/python3"
    if not python_link.is_symlink():
        problems.append("Snap is missing the bin/python3 runtime symlink")
    else:
        target = os.readlink(python_link)
        if not CORE24_PYTHON.fullmatch(target):
            problems.append(
                f"bin/python3 must target core24 Python, found {target!r}"
            )

    return problems


def platform_shadow_problems(snap_root: Path) -> list[str]:
    """Reject libraries that must come from the GNOME content snap."""
    shadows = {
        path.relative_to(snap_root)
        for pattern in GNOME_PLATFORM_SHADOWS
        for path in snap_root.glob(pattern)
    }
    return [
        f"Snap shadows a GNOME platform library: {path}"
        for path in sorted(shadows)
    ]


def desktop_launcher_problems(snap_root: Path) -> list[str]:
    """Validate the desktop launcher generated by Snapcraft."""
    launcher = snap_root / "meta/gui/nvbroadcast.desktop"
    if not launcher.is_file():
        return ["Snap is missing meta/gui/nvbroadcast.desktop"]

    parser = configparser.ConfigParser(interpolation=None)
    try:
        parser.read(launcher, encoding="utf-8")
    except (configparser.Error, OSError, UnicodeError) as error:
        return [f"Snap desktop launcher is invalid: {error}"]

    if not parser.has_section("Desktop Entry"):
        return ["Snap desktop launcher is missing the Desktop Entry section"]

    entry = parser["Desktop Entry"]
    problems: list[str] = []
    exec_value = entry.get("Exec", "")
    try:
        command = shlex.split(exec_value)
    except ValueError as error:
        problems.append(f"Snap desktop launcher has invalid Exec: {error}")
    else:
        if not command or command[0] != "nvbroadcast":
            problems.append(
                "Snap desktop launcher Exec must start with nvbroadcast, "
                f"found {exec_value!r}"
            )

    icon_value = entry.get("Icon", "")
    expected_icon = "${SNAP}/meta/gui/icon.svg"
    if icon_value != expected_icon:
        problems.append(
            f"Snap desktop launcher Icon must be {expected_icon}, "
            f"found {icon_value!r}"
        )
    else:
        icon = snap_root / "meta/gui/icon.svg"
        if not icon.is_file():
            problems.append(
                f"Snap desktop launcher icon does not exist: {icon_value}"
            )
    return problems


def dependency_problems(
    snap_root: Path, platform_machine: str, providers: tuple[str, ...]
) -> tuple[int, list[str]]:
    environment = ArtifactEnvironment.inspect(snap_root, platform_machine)
    if not environment.package_roots:
        return 0, ["no Python package roots were found"]

    problems: list[str] = []

    for package_name, specifier in REQUIRED_RUNTIME.items():
        versions = environment.installed.get(canonicalize_name(package_name), ())
        if not versions:
            problems.append(f"required runtime package is missing: {package_name}{specifier}")
        elif len(versions) != 1:
            problems.append(
                f"required runtime package has multiple owners: "
                f"{package_name} ({', '.join(versions)})"
            )
        elif not any(version in specifier for version in versions):
            problems.append(
                f"{package_name} versions {', '.join(versions)} do not satisfy {specifier}"
            )

    opencv_owners = {
        name: versions
        for name, versions in environment.installed.items()
        if name.startswith("opencv-")
    }
    if set(opencv_owners) != {"opencv-contrib-python"}:
        rendered = ", ".join(
            f"{name} ({', '.join(versions)})"
            for name, versions in sorted(opencv_owners.items())
        )
        problems.append(f"Snap must have exactly one OpenCV owner; found: {rendered}")

    variant = expected_variant(platform_machine)
    contract = RUNTIME_CONTRACTS[variant]
    problems.extend(
        runtime_ownership_problems(variant, environment.installed, providers)
    )
    owner_versions = environment.installed.get(
        canonicalize_name(contract.distribution), ()
    )
    if len(owner_versions) == 1 and owner_versions[0] not in RUNTIME_VERSION:
        problems.append(
            f"{contract.distribution} version {owner_versions[0]} "
            f"does not satisfy {RUNTIME_VERSION}"
        )

    substitutions = (
        {"onnxruntime": "onnxruntime-gpu"}
        if variant is RuntimeVariant.CUDA
        else {}
    )
    problems.extend(environment.dependency_closure_problems(substitutions))
    return len(environment.installed), sorted(set(problems))


def import_problems(package_roots: list[Path]) -> list[str]:
    environment = ArtifactEnvironment(
        package_roots=tuple(package_roots),
        distributions=(),
        installed={},
        markers={},
    )
    return [
        problem.replace("outside the artifact", "outside the Snap")
        for problem in environment.import_problems(IMPORT_PROBES)
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("snap_root", type=Path)
    parser.add_argument(
        "--platform-machine",
        required=True,
        choices=tuple(ARCHITECTURES),
    )
    args = parser.parse_args()

    snap_root = args.snap_root.resolve()
    package_roots = discover_package_roots(snap_root)
    import onnxruntime

    providers = tuple(onnxruntime.get_available_providers())
    count, problems = dependency_problems(
        snap_root, args.platform_machine, providers
    )
    problems.extend(python_runtime_problems(snap_root))
    problems.extend(platform_shadow_problems(snap_root))
    problems.extend(desktop_launcher_problems(snap_root))
    problems.extend(import_problems(package_roots))

    if problems:
        for problem in sorted(set(problems)):
            print(f"ERROR: {problem}", file=sys.stderr)
        return 1

    print(
        f"Validated {count} Python distributions for "
        f"{ARCHITECTURES[args.platform_machine]}; packaging {packaging.__version__}, "
        "single-owner core runtime constraints are satisfied."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
